import { DurableObject } from "cloudflare:workers";
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json;charset=UTF-8","Cache-Control":"no-store"}});
const clean=(v,n=2000)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,n);
const uname=v=>String(v??"").normalize("NFKC").replace(/[\u200B-\u200D\u2060\uFEFF]/g,"").replace(/[\u00A0\u202F]/g,"").trim().toLowerCase();
const id=()=>crypto.randomUUID();
export class ChatRoom extends DurableObject{
 constructor(ctx){super(ctx);this.ctx=ctx;this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at INTEGER NOT NULL,avatar TEXT,vip INTEGER NOT NULL DEFAULT 0,role TEXT NOT NULL DEFAULT 'user');CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,description TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS room_members(room_id TEXT NOT NULL,user_id TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(room_id,user_id));CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL,receiver_id TEXT,room_id TEXT,body TEXT,message_type TEXT NOT NULL DEFAULT 'text',media TEXT,created_at INTEGER NOT NULL,read_at INTEGER);INSERT OR IGNORE INTO rooms(id,name,description,created_at) VALUES('global','اتاق دورهمی','گفتگوی عمومی همه کاربران',strftime('%s','now')*1000);`);for(const q of ["ALTER TABLE users ADD COLUMN avatar TEXT","ALTER TABLE users ADD COLUMN vip INTEGER NOT NULL DEFAULT 0","ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user'","ALTER TABLE messages ADD COLUMN message_type TEXT NOT NULL DEFAULT 'text'","ALTER TABLE messages ADD COLUMN media TEXT","ALTER TABLE messages ADD COLUMN read_at INTEGER"]){try{this.ctx.storage.sql.exec(q)}catch{}}const a=this.ctx.storage.sql.exec("SELECT id FROM users WHERE role='admin' LIMIT 1").toArray()[0];if(!a){const f=this.ctx.storage.sql.exec("SELECT id FROM users ORDER BY created_at LIMIT 1").toArray()[0];if(f)this.ctx.storage.sql.exec("UPDATE users SET role='admin' WHERE id=?",f.id)}}
 user(id){return this.ctx.storage.sql.exec("SELECT id,username,created_at,avatar,vip,role FROM users WHERE id=? LIMIT 1",id).toArray()[0]||null}
 room(id){return this.ctx.storage.sql.exec("SELECT id,name,description,created_at FROM rooms WHERE id=? LIMIT 1",id).toArray()[0]||null}
 member(r,u){return r==='global'||this.ctx.storage.sql.exec("SELECT 1 FROM room_members WHERE room_id=? AND user_id=? LIMIT 1",r,u).toArray().length>0}
 key(a,b){return[a,b].sort().join(':')}
 sel(){return"SELECT m.id,m.sender_id,m.receiver_id,m.room_id,m.body,m.message_type,m.media,m.created_at,m.read_at,u.username,u.avatar FROM messages m LEFT JOIN users u ON u.id=m.sender_id"}
 sockets(){return this.ctx.getWebSockets()}
 send(ws,d){try{ws.send(JSON.stringify(d))}catch{}}
 broadcastPrivate(k,d){const t=JSON.stringify(d);for(const ws of this.sockets()){const a=ws.deserializeAttachment()||{};if(a.privateKey===k)try{ws.send(t)}catch{}}}
 broadcastRoom(r,d){const t=JSON.stringify(d);for(const ws of this.sockets()){const a=ws.deserializeAttachment()||{};if(a.roomId===r)try{ws.send(t)}catch{}}}
 async fetch(req){const u=new URL(req.url);
  if(u.pathname==='/register'&&req.method==='POST'){let d;try{d=await req.json()}catch{return json({ok:false,error:'اطلاعات ثبت‌نام نامعتبر است.'},400)}const n=uname(d.username),p=clean(d.passwordHash,128);if(!/^[\p{L}\p{N}_]{3,24}$/u.test(n))return json({ok:false,error:'نام کاربری باید ۳ تا ۲۴ کاراکتر باشد.'},400);if(!/^[a-f0-9]{64}$/i.test(p))return json({ok:false,error:'رمز عبور معتبر نیست.'},400);if(this.ctx.storage.sql.exec('SELECT id FROM users WHERE username=?',n).toArray().length)return json({ok:false,error:'این نام کاربری قبلاً ثبت شده است.'},409);const first=this.ctx.storage.sql.exec('SELECT id FROM users LIMIT 1').toArray().length===0;const x=id();this.ctx.storage.sql.exec('INSERT INTO users(id,username,password_hash,created_at,avatar,vip,role) VALUES(?,?,?,?,?,?,?)',x,n,p,Date.now(),null,0,first?'admin':'user');return json({ok:true,user:this.user(x)},201)}
  if(u.pathname==='/login'&&req.method==='POST'){let d;try{d=await req.json()}catch{return json({ok:false,error:'اطلاعات ورود نامعتبر است.'},400)}const n=uname(d.username),p=clean(d.passwordHash,128);const x=this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip,role FROM users WHERE username=? AND password_hash=? LIMIT 1',n,p).toArray()[0];return x?json({ok:true,user:x}):json({ok:false,error:'نام کاربری یا رمز عبور اشتباه است.'},401)}
  if(u.pathname==='/me'||u.pathname==='/profile'){const x=this.user(clean(u.searchParams.get('userId'),100));return x?json({ok:true,user:x}):json({ok:false,error:'کاربر پیدا نشد.'},404)}
  if(u.pathname==='/avatar'&&req.method==='POST'){let d;try{d=await req.json()}catch{return json({ok:false,error:'اطلاعات آواتار نامعتبر است.'},400)}const x=clean(d.userId,100),a=String(d.avatar||'');if(!this.user(x))return json({ok:false,error:'کاربر معتبر نیست.'},401);if(a&&(!/^data:image\/(png|jpeg|jpg|webp);base64,/i.test(a)||a.length>700000))return json({ok:false,error:'آواتار نامعتبر یا بزرگ است.'},400);this.ctx.storage.sql.exec('UPDATE users SET avatar=? WHERE id=?',a||null,x);return json({ok:true,user:this.user(x)})}
  if(u.pathname==='/users'){const q=uname(u.searchParams.get('q'));return json({users:this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip,role FROM users WHERE username LIKE ? ORDER BY username LIMIT 50',`%${q}%`).toArray()})}
  if(u.pathname==='/rooms'){const x=clean(u.searchParams.get('userId'),100);return json({rooms:this.ctx.storage.sql.exec("SELECT r.id,r.name,r.description,r.created_at,CASE WHEN r.id='global' THEN 1 ELSE 0 END is_public FROM rooms r WHERE r.id='global' OR EXISTS(SELECT 1 FROM room_members rm WHERE rm.room_id=r.id AND rm.user_id=?) ORDER BY CASE WHEN r.id='global' THEN 0 ELSE 1 END,r.created_at DESC",x).toArray()})}
  if(u.pathname==='/room-messages'){const r=clean(u.searchParams.get('roomId'),100)||'global',x=clean(u.searchParams.get('userId'),100);if(!this.room(r)||!this.member(r,x))return json({ok:false,error:'اتاق پیدا نشد یا عضو نیستید.'},403);return json({messages:this.ctx.storage.sql.exec(`${this.sel()} WHERE m.room_id=? ORDER BY m.created_at DESC LIMIT 100`,r).toArray().reverse()})}
  if(u.pathname==='/private-messages'){const a=clean(u.searchParams.get('userId'),100),b=clean(u.searchParams.get('otherId'),100);if(!this.user(a)||!this.user(b))return json({ok:false,error:'کاربر پیدا نشد.'},404);return json({messages:this.ctx.storage.sql.exec(`${this.sel()} WHERE m.room_id IS NULL AND ((m.sender_id=? AND m.receiver_id=?) OR (m.sender_id=? AND m.receiver_id=?)) ORDER BY m.created_at LIMIT 100`,a,b,b,a).toArray()})}
  if(u.pathname==='/recent-chats'){const x=clean(u.searchParams.get('userId'),100);return json({chats:this.ctx.storage.sql.exec(`SELECT x.other_id,u.username,u.avatar,u.vip,x.body,x.message_type,x.created_at FROM(SELECT CASE WHEN sender_id=? THEN receiver_id ELSE sender_id END other_id,body,message_type,created_at,ROW_NUMBER() OVER(PARTITION BY CASE WHEN sender_id=? THEN receiver_id ELSE sender_id END ORDER BY created_at DESC) rn FROM messages WHERE room_id IS NULL AND(sender_id=? OR receiver_id=?))x LEFT JOIN users u ON u.id=x.other_id WHERE x.rn=1 ORDER BY x.created_at DESC LIMIT 30`,x,x,x,x).toArray()})}
  if(u.pathname==='/admin/stats'||u.pathname==='/admin/users'){const x=this.user(clean(u.searchParams.get('userId'),100));if(!x||x.role!=='admin')return json({ok:false,error:'دسترسی مدیریت ندارید.'},403);if(u.pathname==='/admin/stats')return json({ok:true,users:this.ctx.storage.sql.exec('SELECT COUNT(*) c FROM users').toArray()[0].c,messages:this.ctx.storage.sql.exec('SELECT COUNT(*) c FROM messages').toArray()[0].c,rooms:this.ctx.storage.sql.exec('SELECT COUNT(*) c FROM rooms').toArray()[0].c});return json({ok:true,users:this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip,role FROM users ORDER BY created_at').toArray()})}
  if(u.pathname==='/ws'){if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const x=clean(u.searchParams.get('userId'),100),n=uname(u.searchParams.get('username')),r=clean(u.searchParams.get('roomId'),200)||'global',me=this.user(x);if(!me||me.username!==n)return json({ok:false,error:'نشست کاربر معتبر نیست.'},401);const priv=r.startsWith('private:'),other=priv?clean(r.slice(8),100):null;if(priv){if(!this.user(other)||other===x)return json({ok:false,error:'گفتگوی خصوصی نامعتبر است.'},400)}else if(!this.room(r)||!this.member(r,x))return json({ok:false,error:'اتاق پیدا نشد یا عضو نیستید.'},403);const p=new WebSocketPair(),server=p[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({userId:x,username:n,roomId:priv?null:r,privateKey:priv?this.key(x,other):null,vip:!!me.vip,avatar:me.avatar||null});if(priv){const ms=this.ctx.storage.sql.exec(`${this.sel()} WHERE m.room_id IS NULL AND((m.sender_id=? AND m.receiver_id=?)OR(m.sender_id=? AND m.receiver_id=?)) ORDER BY m.created_at DESC LIMIT 100`,x,other,other,x).toArray().reverse();this.send(server,{type:'history',messages:ms})}else{const ms=this.ctx.storage.sql.exec(`${this.sel()} WHERE m.room_id=? ORDER BY m.created_at DESC LIMIT 100`,r).toArray().reverse();this.send(server,{type:'history',messages:ms})}return new Response(null,{status:101,webSocket:p[0]})}
  return new Response('ChatRoom OK')}
 async webSocketMessage(ws,raw){let d;try{d=typeof raw==='string'?JSON.parse(raw):JSON.parse(new TextDecoder().decode(raw))}catch{return this.send(ws,{type:'error',message:'پیام نامعتبر است.'})}const a=ws.deserializeAttachment()||{},x=a.userId;if(!this.user(x))return; if(d.type==='mark_read'){const m=this.ctx.storage.sql.exec('SELECT id,sender_id,receiver_id,read_at FROM messages WHERE id=?',clean(d.messageId,100)).toArray()[0];if(m&&m.receiver_id===x&&!m.read_at){const t=Date.now();this.ctx.storage.sql.exec('UPDATE messages SET read_at=? WHERE id=?',t,m.id);this.broadcastPrivate(this.key(x,m.sender_id),{type:'message_read',messageId:m.id,read_at:t})}return}
  if(d.type==='private_message'){const to=clean(d.receiverId,100),body=clean(d.body,2000);if(!this.user(to)||to===x||!body)return;const m={id:id(),sender_id:x,receiver_id:to,room_id:null,body,message_type:'text',media:null,created_at:Date.now(),read_at:null,username:a.username,avatar:a.avatar};this.ctx.storage.sql.exec('INSERT INTO messages(id,sender_id,receiver_id,room_id,body,message_type,media,created_at,read_at) VALUES(?,?,?,?,?,?,?,?,?)',m.id,x,to,null,body,'text',null,m.created_at,null);const k=this.key(x,to);this.broadcastPrivate(k,{type:'private_message',message:m});this.broadcastPrivate(k,{type:'message_delivered',messageId:m.id});return}
  if(d.type==='room_message'){const r=a.roomId,body=clean(d.body,2000);if(!r||!this.member(r,x)||!body)return;const m={id:id(),sender_id:x,receiver_id:null,room_id:r,body,message_type:'text',media:null,created_at:Date.now(),read_at:null,username:a.username,avatar:a.avatar};this.ctx.storage.sql.exec('INSERT INTO messages(id,sender_id,receiver_id,room_id,body,message_type,media,created_at,read_at) VALUES(?,?,?,?,?,?,?,?,?)',m.id,x,null,r,body,'text',null,m.created_at,null);this.broadcastRoom(r,{type:'room_message',message:m})}}
 async webSocketClose(){} async webSocketError(){}
}