import { DurableObject } from "cloudflare:workers";
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const c=(v,n=2000)=>String(v??"").replace(/\0/g,"").trim().slice(0,n), norm=v=>c(v,100).normalize("NFKC").replace(/[\u200B-\u200D\u2060\uFEFF]/g,"").toLowerCase(), id=()=>crypto.randomUUID();
export class ChatRoom extends DurableObject{
constructor(ctx,env){super(ctx,env);this.ctx=ctx;ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at INTEGER NOT NULL,avatar TEXT,vip INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,description TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS room_members(room_id TEXT NOT NULL,user_id TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(room_id,user_id));CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL,receiver_id TEXT,room_id TEXT,body TEXT,message_type TEXT NOT NULL DEFAULT 'text',media TEXT,created_at INTEGER NOT NULL,read_at INTEGER);INSERT OR IGNORE INTO rooms VALUES('global','اتاق دورهمی','گفتگوی عمومی همه کاربران',strftime('%s','now')*1000);`);for(const q of ['ALTER TABLE users ADD COLUMN avatar TEXT','ALTER TABLE users ADD COLUMN vip INTEGER NOT NULL DEFAULT 0','ALTER TABLE messages ADD COLUMN message_type TEXT NOT NULL DEFAULT \'text\'','ALTER TABLE messages ADD COLUMN media TEXT','ALTER TABLE messages ADD COLUMN read_at INTEGER'])try{ctx.storage.sql.exec(q)}catch{}}
user(x){return this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip FROM users WHERE id=? LIMIT 1',x).toArray()[0]||null}
room(x){return this.ctx.storage.sql.exec('SELECT id,name,description,created_at FROM rooms WHERE id=? LIMIT 1',x).toArray()[0]||null}
member(r,u){return r==='global'||this.ctx.storage.sql.exec('SELECT 1 FROM room_members WHERE room_id=? AND user_id=? LIMIT 1',r,u).toArray().length>0}
key(a,b){return [a,b].sort().join(':')}
admin(u){const x=this.ctx.storage.sql.exec('SELECT id FROM users ORDER BY created_at LIMIT 1').toArray()[0];return x?.id===u}
select(){return 'SELECT m.id,m.sender_id,m.receiver_id,m.room_id,m.body,m.message_type,m.media,m.created_at,m.read_at,u.username,u.avatar FROM messages m LEFT JOIN users u ON u.id=m.sender_id'}
broadcast(key,d){const s=JSON.stringify(d);for(const w of this.ctx.getWebSockets()){const a=w.deserializeAttachment()||{};if(a.privateKey===key)try{w.send(s)}catch{}}}
async fetch(req){const u=new URL(req.url),p=u.pathname;
if(p==='/register'&&req.method==='POST'){let d;try{d=await req.json()}catch{return json({error:'اطلاعات نامعتبر است.'},400)}const n=norm(d.username),ph=c(d.passwordHash,128);if(!/^[\p{L}\p{N}_]{3,24}$/u.test(n)||!/^[a-f0-9]{64}$/i.test(ph))return json({error:'اطلاعات ثبت‌نام نامعتبر است.'},400);if(this.ctx.storage.sql.exec('SELECT id FROM users WHERE username=?',n).toArray().length)return json({error:'این نام کاربری قبلاً ثبت شده است.'},409);const x=id();this.ctx.storage.sql.exec('INSERT INTO users(id,username,password_hash,created_at,avatar,vip) VALUES(?,?,?,?,?,0)',x,n,ph,Date.now(),null);return json({ok:true,user:this.user(x)},201)}
if(p==='/login'&&req.method==='POST'){let d;try{d=await req.json()}catch{return json({error:'اطلاعات نامعتبر است.'},400)}const x=this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip FROM users WHERE username=? AND password_hash=? LIMIT 1',norm(d.username),c(d.passwordHash,128)).toArray()[0];return x?json({ok:true,user:x}):json({error:'نام کاربری یا رمز عبور اشتباه است.'},401)}
if(p==='/avatar'&&req.method==='POST'){let d;try{d=await req.json()}catch{return json({error:'تصویر نامعتبر است.'},400)}const x=c(d.userId,100),a=String(d.avatar||'');if(!this.user(x))return json({error:'کاربر معتبر نیست.'},401);if(a&&(!/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(a)||a.length>700000))return json({error:'تصویر نامعتبر یا بزرگ است.'},400);this.ctx.storage.sql.exec('UPDATE users SET avatar=? WHERE id=?',a||null,x);return json({ok:true,user:this.user(x)})}
if(p==='/users'){const q=norm(u.searchParams.get('q'));return json({users:this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip FROM users WHERE username LIKE ? ORDER BY username LIMIT 50',`%${q}%`).toArray()})}
if(p==='/rooms'){const x=c(u.searchParams.get('userId'),100);return json({rooms:this.ctx.storage.sql.exec(`SELECT r.id,r.name,r.description,r.created_at FROM rooms r WHERE r.id='global' OR EXISTS(SELECT 1 FROM room_members rm WHERE rm.room_id=r.id AND rm.user_id=?) ORDER BY r.created_at DESC`,x).toArray()})}
if(p==='/room-messages'){const r=c(u.searchParams.get('roomId'),100)||'global',x=c(u.searchParams.get('userId'),100);if(!this.member(r,x))return json({error:'دسترسی ندارید.'},403);return json({messages:this.ctx.storage.sql.exec(`${this.select()} WHERE m.room_id=? ORDER BY m.created_at LIMIT 100`,r).toArray()})}
if(p==='/private-messages'){const a=c(u.searchParams.get('userId'),100),b=c(u.searchParams.get('otherId'),100);return json({messages:this.ctx.storage.sql.exec(`${this.select()} WHERE m.room_id IS NULL AND ((m.sender_id=? AND m.receiver_id=?) OR (m.sender_id=? AND m.receiver_id=?)) ORDER BY m.created_at LIMIT 100`,a,b,b,a).toArray()})}
if(p==='/recent-chats'){const x=c(u.searchParams.get('userId'),100);return json({chats:this.ctx.storage.sql.exec(`SELECT x.other_id,u.username,u.avatar,u.vip,x.body,x.message_type,x.created_at FROM(SELECT CASE WHEN sender_id=? THEN receiver_id ELSE sender_id END other_id,body,message_type,created_at,ROW_NUMBER() OVER(PARTITION BY CASE WHEN sender_id=? THEN receiver_id ELSE sender_id END ORDER BY created_at DESC) rn FROM messages WHERE room_id IS NULL AND(sender_id=? OR receiver_id=?))x JOIN users u ON u.id=x.other_id WHERE x.rn=1 ORDER BY x.created_at DESC LIMIT 30`,x,x,x,x).toArray()})}
if(p==='/admin/stats'){const x=c(u.searchParams.get('userId'),100);if(!this.admin(x))return json({error:'دسترسی مدیریت مجاز نیست.'},403);return json({ok:true,users:this.ctx.storage.sql.exec('SELECT COUNT(*) n FROM users').toArray()[0].n,messages:this.ctx.storage.sql.exec('SELECT COUNT(*) n FROM messages').toArray()[0].n,rooms:this.ctx.storage.sql.exec('SELECT COUNT(*) n FROM rooms').toArray()[0].n})}
if(p==='/admin/users'){const x=c(u.searchParams.get('userId'),100);if(!this.admin(x))return json({error:'دسترسی مدیریت مجاز نیست.'},403);return json({ok:true,users:this.ctx.storage.sql.exec('SELECT id,username,created_at,avatar,vip FROM users ORDER BY created_at').toArray()})}
if(p==='/ws'){if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const x=c(u.searchParams.get('userId'),100),n=norm(u.searchParams.get('username')),r=c(u.searchParams.get('roomId'),100)||'global',me=this.user(x);if(!me||me.username!==n)return json({error:'نشست نامعتبر است.'},401);let pk=null,target=null;if(r.startsWith('private:')){target=c(r.slice(8),100);if(!this.user(target)||target===x)return json({error:'گفتگوی خصوصی نامعتبر است.'},404);pk=this.key(x,target)}else if(!this.member(r,x))return json({error:'دسترسی ندارید.'},403);const pair=new WebSocketPair(),server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({userId:x,username:n,roomId:r,privateKey:pk,vip:!!me.vip,avatar:me.avatar||null});const ms=pk?this.ctx.storage.sql.exec(`${this.select()} WHERE m.room_id IS NULL AND((m.sender_id=? AND m.receiver_id=?)OR(m.sender_id=? AND m.receiver_id=?)) ORDER BY m.created_at LIMIT 100`,x,target,target,x).toArray():this.ctx.storage.sql.exec(`${this.select()} WHERE m.room_id=? ORDER BY m.created_at LIMIT 100`,r).toArray();server.send(JSON.stringify({type:'history',messages:ms}));return new Response(null,{status:101,webSocket:pair[0]})}
return new Response('ChatRoom OK')}
async webSocketMessage(ws,msg){let d;try{d=JSON.parse(typeof msg==='string'?msg:new TextDecoder().decode(msg))}catch{return}const a=ws.deserializeAttachment()||{},x=a.userId;if(d.type==='mark_read'&&a.privateKey){const m=this.ctx.storage.sql.exec('SELECT id,receiver_id,read_at FROM messages WHERE id=?',c(d.messageId,100)).toArray()[0];if(m?.receiver_id===x&&!m.read_at){const now=Date.now();this.ctx.storage.sql.exec('UPDATE messages SET read_at=? WHERE id=?',now,m.id);this.broadcast(a.privateKey,{type:'message_read',messageId:m.id,readAt:now})}return}
if(d.type==='private_message'){const to=c(d.receiverId,100),body=c(d.body,2000);if(!this.user(to)||to===x||!body)return;const m={id:id(),sender_id:x,receiver_id:to,room_id:null,body,message_type:'text',media:null,created_at:Date.now(),read_at:null,username:a.username,avatar:a.avatar||null};this.ctx.storage.sql.exec('INSERT INTO messages(id,sender_id,receiver_id,room_id,body,message_type,media,created_at,read_at) VALUES(?,?,?,?,?,?,?,?,?)',m.id,x,to,null,body,'text',null,m.created_at,null);this.broadcast(this.key(x,to),{type:'private_message',message:m});return}
if(d.type==='room_message'){const r=c(d.roomId,100)||a.roomId,body=c(d.body,2000);if(!this.member(r,x)||!body)return;const m={id:id(),sender_id:x,receiver_id:null,room_id:r,body,message_type:'text',media:null,created_at:Date.now(),read_at:null,username:a.username,avatar:a.avatar||null};this.ctx.storage.sql.exec('INSERT INTO messages(id,sender_id,receiver_id,room_id,body,message_type,media,created_at,read_at) VALUES(?,?,?,?,?,?,?,?,?)',m.id,x,null,r,body,'text',null,m.created_at,null);for(const w of this.ctx.getWebSockets()){const q=w.deserializeAttachment()||{};if(!q.privateKey&&q.roomId===r)try{w.send(JSON.stringify({type:'room_message',message:m}))}catch{}}}}
async webSocketClose(ws){try{ws.close()}catch{}}
async webSocketError(ws){try{ws.close()}catch{}}
}
